### ISSUE TITLE
Simon cuffs drafted too long

### ISSUE THREAD

**Issue by nyergler** [joostdecock/core#184]
I was starting to cut out my Simon pattern when I noticed the cuffs seemed much too long. I redrafted the pattern -- https://freesewing.org/drafts/kcwmg -- with the paperless theme, and the measurement displayed is 4.72" while the cuff is set to be 6.45cm long.

I was able to generate a new draft that appears to be the proper proportion -- https://freesewing.org/drafts/skztf -- but I'm not sure what's the cause of the issue. At first I thought it had to do with metric vs imperial measurements, but I haven't been able to demonstrate that with a test case yet.

**Comment by nyergler** [comment]
After re-drafting my "good" pattern (`skztfz`) using the paperless theme to get measurements, it now displays the same behavior as the other one. I'm attaching the PDF I downloaded before redrafting (which I believe to be correct) 
for comparison.

[freesewing.skztf.a0.pdf](https://github.com/freesewing/core/files/1448803/freesewing.skztf.a0.pdf)

**Comment by joostdecock** [comment]
Thank you Nathan for reporting this and your thorough analysis.

I'll have a look at this later to try to figure out what's going on.

**Comment by joostdecock** [comment]
Ok, I think I know what's going on and it's similar to [issue 158 reported in site](https://github.com/freesewing/site/issues/158).

If you have a look at [your draft page](https://freesewing.org/drafts/kcwmg), you'll see that the model's measurements are in inches (imperial) but the pattern options are in cm (metric).

That's because you are using a model that's set to imperial, but your main account settings are metric.
When mixing these two, it seems there's an issue where options aren't properly converted.

Case in point, the cuff length in your draft is set to 6.45cm. This is passed to core as-is, when it should be converted to imperial because core expects both measurements and options in the same units.

In this case, that's imperial, so your 6.45cm become 6.45 inches. That's about 16.4cm, but core keeps all options within the boundaries configured in the config file. The *cuffLength* option has an [upper boundary](https://github.com/freesewing/core/blob/develop/patterns/Core/SimonShirt/config.yml#L375) of 12cm, so your option is capped at 12cm, and that's what you get in your pattern.

Long story short, you did well to report this because this was so far only reported once and it wasn't that clear to me what was going on.

Now it is, so I'm closing this because the issue is in data/site not in core, and it's essentially a duplicate of [this issue](https://github.com/freesewing/site/issues/158).

A few things you should know:

 - Go to [your account](https://freesewing.org/account), click **Settings** and switch your default units to imperial, and you should no longer have this issue
 - While you spotted the cuffs being wrong, this issue will impact all options in that draft, so you really should not use it like this. (check for your next draft that the options are listed in inches too)
 - I've assigned you both the **issue** and **found-bug** badges in [your profile](https://freesewing.org/users/nxevw). You've earned them :+1:

**Comment by joostdecock** [comment]
FYI: This was fixed in https://github.com/freesewing/data/commit/92c1ebca13eed386105d4ff46ad9ad356f257144

**Comment by nyergler** [comment]
Ah, interesting; thanks for the thorough explanation. I figured it had to be something with imperial vs metric: I somehow got a draft to come out in metric at least once, and when it was metric it was correct.

Anyway, I'll discard that draft, update my settings, and make a new one.

Thanks again for your help, explanation, and hard work on freesewing.

**Comment by joostdecock** [comment]
It's because the bug was only present when *redrafting* and existing draft.

So the behaviour between a new draft, or redrafting a draft (for example to get it with the paperless theme) would have been different.

Your issues are very useful and well researched, it's a pleasure to work on them :+1:
