### ISSUE TITLE
Draft title does not save

### ISSUE THREAD

**Issue by PD75** [joostdecock/core#265]
Title of the draft updates but does not save (reverts when I refresh after saving) when I save a new name(with only letters no strange characters).

https://freesewing.org/drafts/ukymr

/Tiger751023

**Comment by joostdecock** [comment]
Well spotted @PD75  :+1:  

This issue was due to a homophone, it's fixed in https://github.com/freesewing/site/commit/4359bd6bd370433954b51414c6df8822bc52e481

Since you already have the bug badge, I've assigned you the quality-control badge to [your profile](https://freesewing.org/users/Tiger751023).
