### ISSUE TITLE
Unable to clone on Linux

### ISSUE THREAD

**Issue by cloutiy** [joostdecock/core#31]
Following the instructions for installation, I run into the following issue:

```
git clone git@github.com:joostdecock/fso.git
Cloning into 'fso'...
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by joostdecock** [comment]
You're using an SSH repository link, so you'll have to setup an SSH key.
Have you done so? If not, [here's how to do that](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/).
You'll need to add the key to ssh-agent. If it's there, `ssh-add -l` should show it. If not, [here's how to add it](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/#adding-your-SSH-key-to-the-ssh-agent).

If all of this is confusing, you can use an HTTPS link instead. This should work:

`git clone https://cloutiy@github.com/joostdecock/fso.git`

**Comment by cloutiy** [comment]
Super, thanks forthose details Joost.

Not confusing, but I still wasn't able to get it through the SSH repository afet getting my ssh key and adding it to the ssh-agent.

I had to get it from the HTTPS link, but I'm getting 404 errors,and the index.php not rendering as it should:

```
php -S localhost:8000
PHP 7.0.14 Development Server started at Sat Dec 24 10:52:13 2016
Listening on http://localhost:8000
Document root is /home/drifter/dev/fso/docs/demo
Press Ctrl-C to quit.
[Sat Dec 24 10:52:20 2016] ::1:33154 [200]: /
[Sat Dec 24 10:52:20 2016] ::1:33156 [404]: /media/logo.svg - No such file or directory
[Sat Dec 24 10:52:20 2016] ::1:33158 [404]: /css/style.css - No such file or directory
[Sat Dec 24 10:52:20 2016] ::1:33160 [404]: /css/docs.css - No such file or directory
[Sat Dec 24 10:52:20 2016] ::1:33162 [200]: /demo.js
[Sat Dec 24 10:52:20 2016] ::1:33164 [200]: /spinner.gif
[Sat Dec 24 10:52:20 2016] ::1:33166 [404]: /media/logo.svg - No such file or directory
[Sat Dec 24 10:52:20 2016] ::1:33168 [200]: /info/json
```
It seems to be looking for the css and media as subfolders of doc/demo.  But they are of course subfolders of the doc folder.

index.php does have the proper path to those folders though,specifying to look one level up for the media folder:
`<a href='/docs/'><img id='logo' src='../media/logo.svg'></a>`
Still trying to see what's happening there.

Are the SSH repository and HTTPS repository exact copies?

**Comment by joostdecock** [comment]
SSH and HTTPS are just different ways to connect to the same repository. So that does not make a difference.

The problem is probably that your web server has document root `/home/drifter/dev/fso/docs/demo`

You should make that `/home/drifter/dev/fso/docs/demo` The repository should be at the root of the webserver (so that a web request to / lands at the repository).
Now, a request to / serves up the /docs/demo/index.php file, and that's why you get those 404s.

I think ;)

**Comment by cloutiy** [comment]
I had tried that (I think you meant make the root `/home/drifter/dev/fs`?) but the page doesn't get rendered at all. My browser gives me:
```
Firefox has detected that the server is redirecting the request for this address in a way that will never complete.

    This problem can sometimes be caused by disabling or refusing to accept cookies.
```
My cookies are enabled so that can't be it.  But I do get a lot of error messages that point to specific files and functions...at least now I have specifics I can look into:
```
Listening on http://localhost:8000
Document root is /home/drifter/dev/fso
Press Ctrl-C to quit.
[Sat Dec 24 11:38:50 2016] PHP Fatal error:  Uncaught Error: Call to a member function send() on null in /home/drifter/dev/fso/src/Services/DraftService.php:83
Stack trace:
#0 /home/drifter/dev/fso/src/Context/Context.php(93): Freesewing\Services\DraftService->run(Object(Freesewing\Context))
#1 /home/drifter/dev/fso/index.php(19): Freesewing\Context->runService()
#2 {main}
  thrown in /home/drifter/dev/fso/src/Services/DraftService.php on line 83
[Sat Dec 24 11:38:50 2016] ::1:33630 [302]: / - Uncaught Error: Call to a member function send() on null in /home/drifter/dev/fso/src/Services/DraftService.php:83
``` 
Time to troubleshoot :)

**Comment by joostdecock** [comment]
I get it. The demo code depends on the rewriting of URLs (the rules in the htaccess file).
But htaccess is apache specific. Since you are running PHP's internal development server, you don't have rewriting, and thus the demo does not work.

However, if you go to /docs/demo/ I think that page should load.
But what we really need is to make the demo not depend on URL rewriting.
I've created #34 for that, but I am cooking dinner for Xmas eve, so I won't be able to fix that now ;)

**Comment by cloutiy** [comment]
Haha, go cook your dinner man. Joost deCook ;)

Well, glad some good will come out of my misfortune.

**Comment by joostdecock** [comment]
Thanks for your patience @cloutiy, I have pushed update a2895f80a7fc743074391bbcf4e37a95303b2884 which makes the demo work without URL rewriting.

You should get the latest update (`git pull`) and then try again.

**Comment by cloutiy** [comment]
I can run the demo now, thanks Joost. But still not able to open the root.

When generating patterns I notice the text is all bunched up,sometimes
overlapping.

Thought it might just be for french, but it happens in english as well.

Is this still a work in progress,or should I open an issue?

**Comment by joostdecock** [comment]
I'll have a look at the root redirect later to see what's up with that.

For the bunched-up text, that's because the font used in the SVG is not
available on your system.

Traditionally this is not a problem as patterns get converted to PDF server
side, at which point the fonts are embedded in the PDF.

However, it would certainly be better if the fonts were correctly rendered
in the SVG. So feel free to create an issue to improve txt display in the
SVG output.

**Comment by joostdecock** [comment]
Oh, and when you do, you can close this one :)
